version: "3.2"
services:
  php:
    build: 
      context: .
    image: php-sql/shubh-php-mysql-demo:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=shubh-mysql-app
      - MYSQL_USER=shubhuser
      - MYSQL_PASSWORD=shubhpass
      - MYSQL_DB=shubh_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: shubh-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=shubhuser
      - MYSQL_PASSWORD=shubhpass 
      - MYSQL_DATABASE=shubh_db
    container_name: shubh-mysql-app
    volumes:
      - ./db-scripts/:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=shubh-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: shubh-phpmyadmin-app
networks:
  frontend:
  backend:
